revision: 20220824
image_name: arcaflow-plugin-template-python
image_tag: 'test'
project_filepath: /home/jdownie/git/arcaflow-plugin/arcaflow-plugin-template-python
quay_exp: 'never'
registries:
  - url: quay.io
    username_envvar: "QUAY_USERNAME"
    password_envvar: "QUAY_PASSWORD"
    namespace_envvar: "QUAY_NAMESPACE"

