revision: 20220824
image_name: arcaflow-plugin-template-python
image_tag: '0.1.0'
project_filepath: /github/workspace
registries:
  - url: ghcr.io
    username_envvar: "GITHUB_USERNAME"
    password_envvar: "GITHUB_PASSWORD"
  - url: quay.io
    username_envvar: "QUAY_USERNAME"
    password_envvar: "QUAY_PASSWORD"
  # - url: docker.io
  #   username_envvar: "DOCKER_USERNAME"
  #   password_envvar: "DOCKER_PASSWORD"
