# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
project_name: imagebuilder
before:
  hooks:
    - go mod tidy
    - go generate ./...
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    ignore:
      - goos: windows
        goarch: arm64
    main:
      ./carpenter.go
archives:
  - id: my-archive
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md
dockers:
  - dockerfile: Dockerfile.goreleaser
    image_templates:
      - ghcr.io/arcalot/arcaflow-plugin-image-builder:{{ .Tag }}
      - ghcr.io/arcalot/arcaflow-plugin-image-builder:{{ .Major }}
      - ghcr.io/arcalot/arcaflow-plugin-image-builder:latest
checksum:
    name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
release:
  # If set to auto, will mark the release as not ready for production
  # in case there is an indicator for this in the tag e.g. v1.0.0-rc1
  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: auto
  # What to do with the release notes in case the release already exists.
  #
  # Valid options are:
  # - `keep-existing`: keep the existing notes
  # - `append`: append the current release notes to the existing notes
  # - `prepend`: prepend the current release notes to the existing notes
  # - `replace`: replace existing notes
  #
  # Default is `keep-existing`.
  mode: append









