FROM python:3.12.2-slim-bullseye@sha256:6229a3e2fd625bb99efb87e38e7ca4aff6351636ce41b3f229f672b18be8134c

RUN python -m pip install --user --upgrade flake8
    
COPY arcaflow-container-toolkit /
COPY .act.yaml /

ENTRYPOINT ["/arcaflow-container-toolkit"]
