FROM python:3.11.5-slim-bullseye@sha256:9f35f3a6420693c209c11bba63dcf103d88e47ebe0b205336b5168c122967edf

RUN python -m pip install --user --upgrade flake8
    
COPY arcaflow-container-toolkit /
COPY .act.yaml /

ENTRYPOINT ["/arcaflow-container-toolkit"]
