FROM python:3.12.2-slim-bullseye@sha256:1c0da9b35e7fbba5441c9652e93194450f849ba69599dee38ebf9a04c011dc42

RUN python -m pip install --user --upgrade flake8
    
COPY arcaflow-container-toolkit /
COPY .act.yaml /

ENTRYPOINT ["/arcaflow-container-toolkit"]
