name: Continuous Integration
on:
  push:
    branches:
      - main
    tags:
      - v*
  pull_request:
jobs:
  lint_and_test:
    name: lint and test
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_lint_and_test.yaml@update-go-lint-and-test  # FIXME:  SHOULD BE @main
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}

  release:
    name: release
    permissions:
      contents: write
      packages: write
    needs:
      - lint_and_test
    uses: arcalot/arcaflow-reusable-workflows/.github/workflows/go_release.yaml@update-go-lint-and-test  # FIXME:  SHOULD BE @main
    secrets:
      REGISTRY_USERNAME: ${{ github.actor }}
      REGISTRY_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
    with:
      go_version: ${{ vars.ARCALOT_GO_VERSION }}
      for_release: ${{ startsWith(github.event.ref, 'refs/tags/') }}
      registry: ghcr.io
