name: Continuous Integration
on:
  push:
    branches:
      - "**"
    tags:
      - "**"
  pull_request:

jobs:
  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.52.2

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Set up gotestfmt
        uses: gotesttools/gotestfmt-action@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up limgo
        uses: GoTestTools/limgo-action@v1.0.1
        with:
          version: "v1.0.0"
          install-only: true

      - name: Setup go mockgen
        run: go install go.uber.org/mock/mockgen@latest

      - name: generate mocks ce_service
        run: mockgen -source=mocks/ce_service/ce_service.go
      
      - name: generate mocks docker
        run: mockgen -source=mocks/docker/dockerClient.go
      
      - name: generate mocks mock_ce_client
        run: mockgen -source=mocks/mock_ce_client/mock_ce_client.go

      - name: run tests
        run: |
          set -euo pipefail
          go test -coverprofile=test.cov -json -v ./... 2>&1 | tee /tmp/gotest.log | gotestfmt

      - name: upload test log
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-log
          path: /tmp/gotest.log
          if-no-files-found: error

      - name: Calculate test coverage
        run: |
          cat .limgo.json
          limgo -coverfile=test.cov -config=.limgo.json -outfmt=md -outfile=limgo_cov.md
          cat limgo_cov.md >> $GITHUB_STEP_SUMMARY

      - name: upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: limgo_cov.md
          if-no-files-found: error

  release:
    name: release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    needs:
      - golangci-lint
      - test
    if: startsWith(github.event.ref, 'refs/tags/')
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.18

      - name: Setup go mockgen
        run: go install github.com/golang/mock/mockgen@v1.6

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: binaries
          path: dist