name: Limgo Line Coverage
on:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: install flake8
        run: pip3 install --upgrade flake8
      - name: check flake8 is on path
        run: flake8

      # Checkout your project with git
      - name: Checkout
        uses: actions/checkout@v2

      # Install Go on the VM running the action
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Set up limgo - option 2
        uses: GoTestTools/limgo-action@v1.0.1
        with:
          version: "v0.0.3-beta"
          install-only: true

      # Run tests with coverprofile
      - name: Run tests
        run: |
          go test ./... -coverprofile=test.cov

      # Pass the coverprofile to limgo for coverage evaluation
      - name: Check test coverage
        run: |
          cat .limgo.json
          limgo -covfile=test.cov -config=.limgo.json