name: Carpenter Line Coverage
on:
  push:
    branches:
      - "**"
  pull_request:
env:
  target_go_binary: go1.18.1.linux-amd64.tar.gz
jobs:
  code-cov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: show go
        run: ls -alh $(which go)
      - name: show path
        run: echo $PATH
      - name: download target golang
        run: curl -OL https://go.dev/dl/${{ env.target_go_binary }}
      - name: verify binary
        run: sha256sum ${{ env.target_go_binary }}
      - name: extract go directory
        run: |
          sudo tar -C /usr/local -xf ${{ env.target_go_binary }}
      - name: remove old soft link
        run: sudo rm /usr/bin/go
      - name: add new soft link
        run: |
          sudo ln -s /usr/local/go/bin/go /usr/bin/go
          sudo ls -l /usr/local/go/bin/go /usr/bin/go
          export GOPATH=/usr/bin/go
      - name: show version
        run: go version
      - name: install git, make
        run: sudo apt-get -y install git make
      - name: install golang ci lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.50.1
      - name: show golang ci lint
        run: sudo ls ./bin/golangci-lint
      - name: soft link golang ci lint
        run: sudo ln -s .bin/golangci-lint /usr/bin/golangci-lint
      - name: show golang ci lint other
        run: sudo ls /usr/bin/golangci-lint
      - name: verify golang ci lint is on system path
        run: golangci-lint --version
      - name: install limgo
        run: |
          git clone https://github.com/GoTestTools/limgo.git
          cd limgo
          make build
          cd ..
      - name: Checkout source repository
        uses: actions/checkout@v3
      - name: generate coverage data
        run: |
          cd /github/workspace
          go test ./... -coverprofile=cov.out
          ./limgo/limgo -coverfile=cov.out -config=.limgo.json -outfile=limgo_cov.txt
      - name: upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: limgo_cov.txt
          if-no-files-found: error
