name: Carpenter Line Coverage
on:
  push:
    branches:
      - "**"
  pull_request:
#env:
#  target_go_binary: go1.18.1.linux-amd64.tar.gz
jobs:
  code-cov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: remove old golang
        run: |
          sudo rm -rf /usr/local/go
          sudo rm -f /usr/bin/go
      - name: download golang 1.18
        run: curl -OL https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
      - name: verify binary
        run: sha256sum go1.18.1.linux-amd64.tar.gz
      - name: extract go directory
        run: sudo tar -C /usr/local -xvf go1.18.1.linux-amd64.tar.gz
      - name: add golang to path
        run: |
          echo 'export PATH=$PATH:/usr/local/go/bin' >> ~/.profile
          source ~/.profile
      - name: show version
        run: go version


