name: Carpenter Line Coverage
on:
  push:
    branches:
      - "**"
#  pull_request:
#env:
#  target_go_binary: go1.18.1.linux-amd64.tar.gz
jobs:
  code-cov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: show go
        run: ls -alh $(which go)
      - name: show path
        run: echo $PATH
      - name: download golang 1.18
        run: curl -OL https://go.dev/dl/go1.18.1.linux-amd64.tar.gz
      - name: verify binary
        run: sha256sum go1.18.1.linux-amd64.tar.gz
      - name: extract go directory
        run: |
          sudo tar -C /usr/local -xf go1.18.1.linux-amd64.tar.gz
      - name: add soft link
        run: |
          rm /usr/bin/go
          ln -s /usr/local/go/bin/go /usr/bin/go
          ln -l /usr/local/go/bin/go /usr/bin/go
      - name: show version
        run: go version


