name: Carpenter Line Coverage
on:
  push:
    branches:
      - "**"
  pull_request:
env:
  target_go_binary: go1.18.1.linux-amd64.tar.gz
jobs:
  code-cov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: show go
        run: ls -alh $(which go)
      - name: show path
        run: echo $PATH
      - name: download target golang
        run: curl -OL https://go.dev/dl/${{ env.target_go_binary }}
      - name: verify binary
        run: sha256sum ${{ env.target_go_binary }}
      - name: extract go directory
        run: |
          sudo tar -C /usr/local -xf ${{ env.target_go_binary }}
      - name: remove old soft link
        run: sudo rm /usr/bin/go
      - name: add new soft link
        run: |
          sudo ln -s /usr/local/go/bin/go /usr/bin/go
          sudo ls -l /usr/local/go/bin/go /usr/bin/go
      - name: show version
        run: go version


