name: Carpenter Line Coverage
on:
  push:
    branches:
      - "**"
  pull_request:
jobs:
  code-cov:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: build carpenter image
        run: |
          docker build --tag carpenter .
          docker create --name test carpenter
          docker cp test:/limgo_cov.txt .
          docker rm test
          cat limgo_cov.txt >> $GITHUB_STEP_SUMMARY
      - name: upload coverage results
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: limgo_cov.txt
          if-no-files-found: error

