name: Act Reusable Workflow to Build and Push Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      quay_img_exp:
        required: true
        type: string
      quay_custom_namespace:
        required: false
        type: string
      github_username:
        required: false
        type: string
      github_namespace:
        required: false
        type: string    
    secrets:
      QUAY_NAMESPACE:
        required: false
      QUAY_USERNAME:
        required: false
      QUAY_PASSWORD:
        required: false

env:
  IMAGE_NAME: ${{ inputs.image_name }}
  IMAGE_TAG: ${{ inputs.image_tag }}
  QUAY_IMG_EXP: ${{ inputs.quay_img_exp }}
  GITHUB_USERNAME: ${{ inputs.github_username }}
  GITHUB_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
  GITHUB_NAMESPACE: ${{ inputs.github_namespace }}
  QUAY_NAMESPACE: ${{ secrets.QUAY_NAMESPACE }}
  QUAY_CUSTOM_NAMESPACE: ${{ inputs.quay_custom_namespace }}
  QUAY_USERNAME: ${{ secrets.QUAY_USERNAME }}
  QUAY_PASSWORD: ${{ secrets.QUAY_PASSWORD }}
jobs:
  act-build:
    name: Build ${{ github.ref_name }} from ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set image tag for release
        if: github.event_name == 'release'
        run: |
          echo "IMAGE_TAG=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set image tag and expiration for dev
        if: github.ref != 'refs/heads/main' && github.event_name != 'release'
        run: |
          export commit_hash=${{ github.sha }}
          echo "IMAGE_TAG=${GITHUB_REF##*/}_${commit_hash:0:7}" >> $GITHUB_ENV
          echo "QUAY_IMG_EXP=90d" >> $GITHUB_ENV
      - name: Checkout this project
        uses: actions/checkout@v3
      - name: act build
        uses: arcalot/arcaflow-container-toolkit@main
        with:
          args: build --build --push
