name: ACT Reusable Workflow to Build and Push Image
on:
  workflow_call:
    inputs:
      image_name:
        required: true
        type: string
      image_tag:
        required: true
        type: string
      quay_img_exp:
        required: false
        type: string
      quay_custom_namespace:
        required: false
        type: string
      github_username:
        required: false
        type: string
      github_namespace:
        required: false
        type: string
      archetype:
        required: false
        type: string
      multi_arch:
        required: false
        type: boolean   
    secrets:
      QUAY_NAMESPACE:
        required: false
      QUAY_USERNAME:
        required: false
      QUAY_PASSWORD:
        required: false

env:
  QUAY_TAG_ROOT: quay.io/${{ secrets.QUAY_NAMESPACE }}/${{ inputs.image_name }}
  QUAY_IMG_EXP: 0
  BUILD_PLATFORMS: linux/amd64, linux/arm64

jobs:
  act-build:
    name: Build ${{ github.ref_name }} from ${{ github.event_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Set image tags for release
        if: github.event_name == 'release'
        run: |
          echo "IMAGE_TAGS=${{ env.QUAY_TAG_ROOT }}:${GITHUB_REF#refs/*/} ${{ env.QUAY_TAG_ROOT }}:latest" >> $GITHUB_ENV
      
      - name: Set image tags for main
        if: github.ref == 'refs/heads/main' && github.event_name != 'release'
        run: |
          echo "IMAGE_TAGS=${{ env.QUAY_TAG_ROOT }}:main_latest" >> $GITHUB_ENV

      - name: Set image tags and expiration for dev
        if: github.ref != 'refs/heads/main' && github.event_name != 'release'
        run: |
          export commit_hash=${{ github.sha }}
          echo "QUAY_IMG_EXP=90d" >> $GITHUB_ENV
          echo "IMAGE_TAGS=${{ env.QUAY_TAG_ROOT }}:${GITHUB_REF##*/}_${commit_hash:0:7}" >> $GITHUB_ENV
      
      - name: Checkout this project
        uses: actions/checkout@v4
        
      - name: arcaflow-container-toolkit-action
        uses: arcalot/arcaflow-container-toolkit-action@v1.4.0
        with:
          image_name: ${{ inputs.image_name }}
          image_tag: ${{ inputs.image_tag }}
          github_username: ${{ inputs.github_username }}
          github_password: ${{ secrets.GITHUB_TOKEN }}
          github_namespace: ${{ inputs.github_namespace }}
          quay_username: ${{ secrets.QUAY_USERNAME }}
          quay_password: ${{ secrets.QUAY_PASSWORD }}
          quay_namespace: ${{ secrets.QUAY_NAMESPACE }}
          quay_custom_namespace: ${{ inputs.quay_custom_namespace }}
          quay_img_exp: ${{ inputs.quay_img_exp }}
          build_timeout: ${{ inputs.build_timeout }}
          archetype: ${{ inputs.archetype }}
          req_check_only: ${{ inputs.multi_arch }}

      - name: Install qemu dependency
        run: |
          sudo apt-get update
          sudo apt-get install -y qemu-user-static

      - name: Log in to quay.io
        uses: redhat-actions/podman-login@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_PASSWORD }}
      
      - name: Build multi-arch image
        id: build-multi-arch
        uses: redhat-actions/buildah-build@v2
        with:
          context: .
          platforms: ${{ env.BUILD_PLATFORMS }}
          tags: ${{ env.IMAGE_TAGS }}
          containerfiles: |
            ./Dockerfile
          labels: quay.expires-after=${{ env.QUAY_IMG_EXP }}
      
      - name: Push image to quay.io
        uses: redhat-actions/push-to-registry@v2
        with:
          image: ${{ steps.build-multi-arch.outputs.image }}
          tags: ${{ steps.build-multi-arch.outputs.tags }}
